version: '2.1'

services:
  micros:
    build: .
    mem_limit: 1024m
    ports:
      - "8080:8080"
  #  environment: ##reactive cela quand tu auras configurer les profiles docker-dev et docker-prod
   #   - SPRING_PROFILES_ACTIVE=docker ##reactive cela quand tu auras configurer les profiles docker-dev et docker-prod
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres
    mem_limit: 1024m
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "psql -h 'localhost' -U 'postgres' -c '\\l'"]
      interval: 30s
      timeout: 30s
      retries: 3    